from db import get_db_connection

def snake_case(str):
    return str.strip().replace(" ", "_").lower().replace('-','_')

def generate_columns():
    dict = {
        'id': None,
        'address': None,
        'district': None,
        'city': None,
        'zip_code': None,
        'country': None,
        'latitude': None,
        'longitude': None,
        'published': None,
        'asuinpinta-ala': None, 
        'asumistyyppi': None, 
        'asunnossa_sauna': None, 
        'autopaikan_kustannukset': None, 
        'energialuokka': None, 
        'energiatodistus': None, 
        'ensiesittelyssä': None, 
        'hissi': None, 
        'hoitovastike': None, 
        'huoneistojen_lukumäärä': None, 
        'huoneiston_kokoonpano': None, 
        'huoneita': None, 
        'ikkunoiden_suunta': None, 
        'ilmanvaihto': None, 
        'ilmastointijärjestelmä': None, 
        'isännöinti': None, 
        'kaavatilanne': None, 
        'kaavoitustiedot': None, 
        'kattomateriaali': None, 
        'kattotyyppi': None, 
        'kaupunginosa': None, 
        'keittiön_lattia': None, 
        'keittiön_seinä': None, 
        'keittiön_varusteet': None, 
        'kerroksia': None, 
        'kerroksien_lukumäärä': None, 
        'kerros': None, 
        'kiinnitykset': None, 
        'kiinteistön_antennijärjestelmä': None, 
        'kiinteistönhoito': None, 
        'kiinteistötunnus': None, 
        'kiinteistövero': None, 
        'kohde_on': None, 
        'kohdenumero': None, 
        'kokonaispinta-ala': None, 
        'kunnallistekniikka': None, 
        'kunnon_lisätiedot': None, 
        'kunto': None, 
        'kuntotutkimus': None, 
        'kylpyhuoneen_lattia': None, 
        'kylpyhuoneen_seinät': None, 
        'kylpyhuoneen_varusteet': None, 
        'käyttövastike': None, 
        'liikehuoneistojen_lukumäärä': None, 
        'liikehuoneistojen_pinta-ala': None, 
        'liikenneyhteydet': None, 
        'liiketilojen_pinta-ala': None, 
        'linkit': None, 
        'lisätiedot': None, 
        'lisätietoa_taloyhtiöstä': None, 
        'lisätietoa_vapautumisesta': None, 
        'lisätietoja_lämmityksestä': None, 
        'lisätietoja_makuuhuoneen_varusteista': None, 
        'lisätietoja_talosta': None, 
        'lunastuspykälä': None, 
        'lämmitys': None, 
        'lämmityskustannukset': None, 
        'lämmönjakelu': None, 
        'maanvuokraaja': None, 
        'maasto': None, 
        'makuuhuoneen_lattia': None, 
        'makuuhuoneen_seinät': None, 
        'muut_kustannukset': None, 
        'muut_rakennukset': None, 
        'muut_tilat': None, 
        'myyntihinta': None, 
        'neliöhinta': None, 
        'näkymät': None, 
        'olohuoneen_lattia': None, 
        'olohuoneen_seinät': None, 
        'olohuoneen_varusteet': None, 
        'ominaisuudet': None, 
        'onko_osuus_lunastettu': None, 
        'onko_osuus_tontista_lunastettu': None, 
        'osakeluettelo_on_siirretty_huoneistojärjestelmään': None, 
        'palvelut': None, 
        'parveke': None, 
        'parvekkeen_lisätiedot': None, 
        'perustus': None, 
        'pihan_ilmansuunnat': None, 
        'pinta-alan_lähde': None, 
        'pinta-alojen_lisätiedot': None, 
        'pintamateriaalit': None, 
        'postitoimipaikka': None, 
        'puhtaanapito': None, 
        'pysäköintitilan_kuvaus': None, 
        'pääomavastike': None, 
        'rakennuksen_käyttöönottovuosi': None, 
        'rakennuksen_tyyppi': None, 
        'rakennusmateriaali': None, 
        'rakennusoikeus': None, 
        'rakennusvuoden_lisätiedot': None, 
        'rakennusvuosi': None, 
        'rannan_omistus': None, 
        'saunamaksu': None, 
        'saunan_kustannukset': None, 
        'saunan_lisätiedot': None, 
        'sijainti': None, 
        'sähköinen_omistajamerkintä': None, 
        'säilytystilat': None, 
        'taloyhtiön_nimi': None, 
        'taloyhtiön_tilat_ja_tuotot': None, 
        'taloyhtiössä_on_sauna': None, 
        'tehdyt_remontit': None, 
        'tiedustelut': None, 
        'tietoliikennepalvelut': None, 
        'tontin_koko': None, 
        'tontin_kuvaus': None, 
        'tontin_omistus': None, 
        'tontin_pinta-ala': None, 
        'tontin_vuokra': None, 
        'tontin_vuokra_päättyy': None, 
        'tontin_vuokravastike': None, 
        'tulevat_remontit': None, 
        'tv-palvelut': None, 
        'uudiskohde': None, 
        'valinnaisen_vuokratontin_lunastusosuus': None, 
        'vapautuu': None, 
        'velaton_hinta': None, 
        'velkaosuus': None, 
        'vesi_ja_jätevesi': None, 
        'vesimaksu': None, 
        'vesimaksun_lisätiedot': None, 
        'viemäröinti': None, 
        'vuokra-aika': None, 
        'vuokratontin_lunastusosuus': None, 
        'vuokrattu': None, 
        'yhteiset_tilat': None, 
        'yhtiövastike_yhteensä': None, 
    }
    columns = dict.keys()
    for col in columns:
        col = snake_case(col)
        print(col)

    with get_db_connection() as conn:
        with conn.cursor() as cur:
            for col in columns:
                col = snake_case(col)
                print(col)
                cur.execute(
                    f"""
                        ALTER TABLE listing 
                        ADD COLUMN IF NOT EXISTS 
                        {col} TEXT;
                    """,
                )

            conn.commit()